# Site settings
title: putusudarma blog | My Train Of Thought
email: mafaikmon@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://putusudarma.me"
twitter_username: putusudarma
github_username:  mafaik

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
