# Site settings
title: putusudarma
email: yo@putusudarma.me
description: "Just a healthy normal man. Interested in website development and computer networking. Love doing parkour and a guitarist for Sweet Tone Trio."
baseurl: ""
url: "http://putusudarma.me"
twitter_username: putusudarma
github_username:  mafaik

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
highlighter: rouge